version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
  - dependency-name: rails
    versions:
    - 6.1.3
